name: filter-m3u

on:
  schedule:
    - cron: "0 */12 * * *"      # 每 12 小时整点
  workflow_dispatch:           # 允许手动触发（测试用）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Run filter
        run: python filter_m3u.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git
          git pull --rebase origin main   # 先拉取并自动 rebase
          git add live.m3u
          git diff --cached --quiet || (git commit -m "auto update" && git push)
