name: filter-m3u

on:
  schedule:
    # 北京时间 00:00, 06:00, 12:00, 18:00 运行
    # 转换为 UTC 时间是 16:00, 22:00, 04:00, 10:00
    - cron: '0 16 * * *'
    - cron: '0 22 * * *'
    - cron: '0 4 * * *'
    - cron: '0 10 * * *'
  workflow_dispatch:           # 允许手动触发（测试用）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Run filter
        run: python filter_m3u.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git
          # 先提交本地变更，再拉取远程，最后推送
          git add live.m3u
          git diff --cached --quiet || git commit -m "auto update $(date -u +%F_%H:%M)"
          git pull --rebase origin main || true
          git push
